pipeline{   
    agent any
    
    options {
        ansiColor('xterm')
    }
    
    stages{
        stage('terraform init'){
            steps{
                bat "terraform init -upgrade"
            }
        }       
        stage('terraform plan'){
            steps{
                bat 'terraform plan'
            }
        }
        stage('pull-request details'){
            steps{
                bat"""
                    echo 'pull id:'%ghprbPullId%
                    echo 'Commit Author:'%ghprbActualCommitAuthor%
                    echo 'Commit Author Email:'%ghprbActualCommitAuthorEmail%
                    echo 'Source Branch:'%ghprbSourceBranch%
                    echo 'Target Branch:'%ghprbTargetBranch%
                """
            }
        }     
    }
}

