pipeline{   
    agent any
    
    options {
        ansiColor('xterm')
    }
    
    stages{
        stage('terraform init'){
            steps{
                bat "terraform init -upgrade"
            }
        }       
        stage('terraform plan'){
            steps{
                bat 'terraform plan'
            }
        }
        stage('pull-request details'){
            steps{
                bat "echo 'pull id:'%ghprbPullId%"
                bat "echo 'Commit Author:'%ghprbActualCommitAuthor%"
                bat "echo 'Commit Author Email:'%ghprbActualCommitAuthorEmail%"
                bat "echo 'Source Branch:'%ghprbSourceBranch%"
                bat "echo 'Target Branch:'%ghprbTargetBranch%"
            }
        }     
    }
}

